name: Deploy to Firebase Hosting and Firestore Rules

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Write Firebase service account
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_HESABI_APP_EDC7E }}' > ${{ runner.temp }}/firebase-key.json

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy Hosting and Firestore Rules
        run: firebase deploy --only hosting,firestore:rules --project hesabi-app-edc7e
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/firebase-key.json
